{"name": "test_Login_with_Invalid_UserName", "status": "failed", "statusDetails": {"message": "AssertionError: False != True", "trace": "self = <Test_Cases.test_LoginPage.Github_Login_Functionality_validation testMethod=test_Login_with_Invalid_UserName>\n\n    def test_Login_with_Invalid_UserName(self):\n        self.driver.get(self.baseURL)\n        parameter1 = str(config['sign_in']['invalid_email'])\n        parameter2 = str(config['sign_in']['password'])\n        self.lp.UserLogin(parameter1, parameter2)\n        time.sleep(5)\n        result = self.lp.VerifyLogin()\n>       self.assertEqual(result, True)\nE       AssertionError: False != True\n\ntest_LoginPage.py:72: AssertionError"}, "attachments": [{"name": "log", "source": "986d4634-0c08-4aa2-914b-462ba3bdfa24-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "967a1e51-a761-42c0-8258-ccfbd781c660-attachment.txt", "type": "text/plain"}], "start": 1559837146524, "stop": 1559837169830, "uuid": "d31d420a-e1ec-4db2-9c33-4193a6160acd", "historyId": "453fc10f54504c3d12d8cfb40fc51e1e", "fullName": "test_LoginPage.Github_Login_Functionality_validation#test_Login_with_Invalid_UserName", "labels": [{"name": "suite", "value": "test_LoginPage"}, {"name": "subSuite", "value": "Github_Login_Functionality_validation"}, {"name": "host", "value": "WKMIN7880754"}, {"name": "thread", "value": "36785-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_LoginPage"}]}